---
# adapted from:
# - https://github.com/marketplace/actions/install-nix#usage
# - https://simonwillison.net/2020/Oct/9/git-scraping/
name: "fetch info from start.gg api"
on:
  schedule:
  - cron:  '*/30 * * * *'
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v15
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: configure git
      run: |
        git config user.name "randall the cloud"
        git config user.email actions@users.noreply.github.com
    - name: fetch info from api
      run: cd rust && nix-shell -p rustc cargo --run "cargo run > ../docs/events.json"
      env:
        GRAPHQL_API_TOKEN: ${{ secrets.GRAPHQL_API_TOKEN }}
    - name: push changes
      run: |
        git add docs/events.json
        git commit -m "fetched: $(date -u)" || exit 0
        git push || true
