---
# adapted from:
# - https://github.com/marketplace/actions/install-nix#usage
name: "build netplay-bracket-finder crate"
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
    - name: install rust
      run: |
        # install rustup
        curl --proto '=https' --tlsv1.2 --retry 10 --retry-connrefused -fsSL "https://sh.rustup.rs" | sh -s -- --default-toolchain none -y
        echo "${CARGO_HOME:-$HOME/.cargo}/bin" >> $GITHUB_PATH

        # install nightly
        rustup toolchain install nightly --allow-downgrade --profile minimal --component clippy

    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: build netplay-bracket-finder
      run: |
        # fetch dependencies
        cd rust && cargo build --release
    - name: upload artifact
      uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # v3
      with:
        name: netplay-bracket-finder-x86_64-linux
        path: rust/target/release/netplay-bracket-finder
